services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
    volumes:
      - db_data:/var/lib/mysql

  pma:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: mysql
    depends_on:
      - db

  app:
    build: .
    image: shitty_app_with_db:1.0
    ports:
      - "3000:3000"
    volumes:
      - "./src:/app/src"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: mysql
      DB_NAME: db
      DB_PORT: 3306
      PORT: 3000
    depends_on:
      - db

volumes:
  db_data:
